### ISSUE TITLE
'wsl.exe' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by stuartleeks** [Tyriar/vscode-windows-terminal#23]
When I have a project open with Remote-WSL and attempt to run the "Windows Terminal:Open" command, I get the following error:

```
[2020-06-27 14:32:35.405] [renderer12] [error] Command failed: wsl.exe -d ubuntu-20.04 wslpath -w /home/stuart/source/devcontainer-cli
'wsl.exe' is not recognized as an internal or external command,
operable program or batch file.
: Error: Command failed: wsl.exe -d ubuntu-20.04 wslpath -w /home/stuart/source/devcontainer-cli
'wsl.exe' is not recognized as an internal or external command,
operable program or batch file.

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

`wsl.exe` is in my path - I can run `wsl.exe` via Start/Run and it resolves via the path.

Let me know if any further info would be useful to debug this :-)

**Comment by stuartleeks** [comment]
I'm now seeing the same error loading the devcontainer in that VS Code installation so I think this is an issue related to my system/vscode installation. It works fine on another machine and in VS Code Insiders, so I'm going to close this.
